import type { IconType } from "react-icons";
import {
  FaBook,
  FaBrain,
  FaCodeBranch,
  FaCreditCard,
  FaDatabase,
  FaDesktop,
  FaFileAlt,
  FaFlask,
  FaLayerGroup,
  FaLock,
  FaNetworkWired,
  FaRobot,
  FaServer,
  FaShieldAlt,
} from "react-icons/fa";
import {
  SiDjango,
  SiDotnet,
  SiFirebase,
  SiFilament,
  SiGit,
  SiGithub,
  SiHtml5,
  SiJavascript,
  SiLangchain,
  SiLaravel,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiPandas,
  SiPhp,
  SiPython,
  SiReact,
  SiScikitlearn,
  SiStatamic,
  SiTailwindcss,
  SiTypescript,
  SiVuedotjs,
} from "react-icons/si";

const techIcons: Record<string, IconType> = {
  ".NET Core": SiDotnet,
  "AI Workflows": FaRobot,
  Authentication: FaLock,
  Authorization: FaShieldAlt,
  Django: SiDjango,
  Embeddings: FaBrain,
  Filament: SiFilament,
  Firebase: SiFirebase,
  Git: SiGit,
  GitHub: SiGithub,
  HTML: SiHtml5,
  "Laravel 13": SiLaravel,
  "Laravel AI": FaRobot,
  Laravel: SiLaravel,
  "Laravel Nova": FaLayerGroup,
  LangChain: SiLangchain,
  "Blade Components": FaLayerGroup,
  "Blade Templating": SiLaravel,
  "CSS3": SiTailwindcss,
  Debugging: FaFlask,
  MongoDB: SiMongodb,
  "MVC Architecture": FaNetworkWired,
  MySQL: SiMysql,
  "Next.js": SiNextdotjs,
  OpenAI: FaRobot,
  "Pest": FaFlask,
  PHP: SiPhp,
  "Payment Integrations": FaCreditCard,
  Pandas: SiPandas,
  Python: SiPython,
  "Query Optimization": FaDatabase,
  RBAC: FaShieldAlt,
  React: SiReact,
  "React 19": SiReact,
  "REST APIs": FaServer,
  "Relational Data Modeling": FaDatabase,
  SQL: FaDatabase,
  "Scikit-learn": SiScikitlearn,
  Statamic: SiStatamic,
  "Technical Documentation": FaFileAlt,
  "Tailwind CSS": SiTailwindcss,
  "Third-Party API Integration": FaServer,
  TypeScript: SiTypescript,
  "Unit Testing": FaFlask,
  "Vue.js": SiVuedotjs,
  Vue: SiVuedotjs,
  XGBoost: FaBrain,
  JavaScript: SiJavascript,
  "Code Reviews": FaCodeBranch,
  "Full-Stack Delivery": FaLayerGroup,
  "Data and ML": FaBrain,
  "Backend Systems": FaServer,
  "Data Stores": FaDatabase,
  "Eloquent ORM": FaDatabase,
  "HTML5": SiHtml5,
  "Responsive Admin UI": FaDesktop,
  "Tools and Workflow": FaBook,
};

export function getTechIcon(name: string): IconType | null {
  return techIcons[name] ?? null;
}
